[package]
name = "resp"
version = "0.0.1"
description = "A RESP (REdis Serialization Protocol) parser for Rust"
authors = ["DavidCai <davidcai1993@yahoo.com>"]
readme = "README.md"
repository = "https://github.com/DavidCai1993/resp.rs"
license = "MIT"

[dependencies]
